name: Publish Shared Lib
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@fiap-pos-front-end"
      - name: Install and build
        run: |
          npm ci
          npm run build
      - name: Configure npm for GitHub Packages
        run: |
          echo "@fiap-pos-front-end:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          npm publish
